#!/bin/sh
ln -s $HOME/.dotfiles/omf $HOME/.config/omf
ln -s $HOME/.dotfiles/vimrc $HOME/.vimrc
ln -s $HOME/.dotfiles/vimrc.plugins $HOME/.vimrc.plugins
ln -s $HOME/.dotfiles/tmux.conf $HOME/.tmux.conf
ln -s $HOME/.dotfiles/tmux.status.conf $HOME/.tmux.status.conf
ln -s $HOME/.dotfiles/zshrc $HOME/.zshrc
ln -s $HOME/.dotfiles/scm_breeze $HOME/.scm_breeze
ln -s $HOME/.dotfiles/git.scmbrc $HOME/.git.scmbrc
